[package]
name = "semver-swift-bridge"
version = "1.0.6"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
swift-bridge = "0.1"
semver = "1.0.6"
